affi=\
{
    "Alpha-2:Defense": "Boston University",
    "BARI": "Northeastern University",
    "BOP": "Harvard University",
    "BMI": "MOC",
    "BuechlerResearchh": "Boston University",
    "Cloud Scheduler": "Northeastern University",
    "DTicToc": "MIT",
    "Dataverse": "MOC",
    "Elastic Prototype": "Boston University",
    "Engage1-Research": "MOC",
    "Hanscom": "US Air Force",
    "Mix&Match Federation": "MOC",
    "MOC Monitoring (MOCMon) Platform v2.0": "MOC",
    "MOCSystemMonitoring": "MOC",
    "NLP": "Boston University",
    "NYC Subways": "Boston University",
    "Network Programmability": "Northeastern University",
    "Network traffic collection in the MOC": "Northeastern University",
    "PRIMES": "Boston University",
    "Rado": "MOC",
    "SAIL": "Boston University",
    "SAIL-twitter-toolkit": "Boston University",
    "Secure Cloud": "Boston University",
    "SoftwareDiscovery": "MOC",
    "_knikolla": "MOC",
    "abyrne19": "Boston University",
    "admin": "MOC",
    "alt_demo": "MOC",
    "ankitsh@bu.edu": "Boston University",
    "ataturk": "MOC",
    "ccs-musketeer-demo": "Boston University",
    "chen.ruo": "MOC",
    "cloud-dataverse": "MOC",
    "cms": "MOC",
    "cnh": "MIT",
    "cons3rt": "Jackpine Technologies",
    "culbertj": "MGHPCC",
    "dasmith@ccs.neu.edu": "Northeastern University",
    "demo": "MOC",
    "fjansen": "Boston University",
    "frascog": "Boston University",
    "g.wang.china86": "University of Connecticut",
    "gshock@bu.edu": "Boston University",
    "gsilvis": "MOC",
    "henn": "MOC",
    "hpc": "MOC",
    "jfreud@bu.edu": "MOC",
    "jtgoodhue": "MGHPCC",
    "k2k": "MOC",
    "kamfonik": "MOC",
    "kapalavai.n@husky.neu.edu": "MOC",
    "katlaparthi.s": "MOC",
    "lapets": "Boston University",
    "larry.rudolph": "TwoSigma",
    "malte@csail.mit.edu": "MIT",
    "moc": "MOC",
    "naved001": "MOC",
    "nickolai": "MIT",
    "nikolaj": "Boston University",
    "okrieg": "MOC",
    "pjd@ccs.neu.edu": "MOC",
    "prajwal.maredukonda@philips.com": "Philips",
    "rahuls": "MOC",
    "ravig": "MOC",
    "ron.unrau": "General User",
    "rotemh": "MIT",
    "services": "MOC",
    "shreyap": "Boston University",
    "shwsun": "MOC",
    "small-brain": "Boston University",
    "sscheff": "Boston University",
    "supraja.krishnan7": "Northeastern University",
    "trtiwari@bu.edu": "MOC",
    "tutorial_2016": "MOC",
    "tutorial_project": "MOC",
    "tyroneh": "Boston University",
    "varia": "Boston University",
    "vinodv": "MIT",
    "weinbe2@bu.edu": "Boston University"
}


