affi=\
{
    "Alpha-2:Defense": "Boston University",
    "Alina(NEU)": "Northeastern University",
    "BARI": "Northeastern University",
    "BOP": "Harvard University",
    "BMI": "MOC",
    "BuechlerResearchh": "Boston University",
    "Cloud Scheduler": "Northeastern University",
    "DTicToc": "MIT",
    "Dataverse": "MOC",
    "DiSc": "Boston University",
    "Elastic Prototype": "Boston University",
    "Engage1-Research": "MOC",
    "Hanscom": "US Air Force",
    "Mix&Match Federation": "MOC",
    "MOC Monitoring (MOCMon) Platform v2.0": "MOC",
    "MOCSystemMonitoring": "MOC",
    "NLP": "Boston University",
    "NYC Subways": "Boston University",
    "Network Programmability": "Northeastern University",
    "Network traffic collection in the MOC": "Northeastern University",
    "NFV-SDN": "MIT Lincoln lab",
    "PRIMES": "Boston University",
    "Rado": "MOC",
    "SAIL": "Boston University",
    "SAIL-twitter-toolkit": "Boston University",
    "Secure Cloud": "Boston University",
    "SoftwareDiscovery": "MOC",
    "_knikolla": "MOC",
    "abyrne19": "Boston University",
    "admin": "MOC",
    "alt_demo": "MOC",
    "ankitsh@bu.edu": "Boston University",
    "ataturk": "MOC",
    "b0rracha": "Boston University",
    "burstein": "Boston University", 
    "ccs-musketeer-demo": "Boston University",
    "chen.ruo": "MOC",
    "chhari": "Boston University",
    "Cloud Scheduler": "Northeastern University",
    "cloud-dataverse": "MOC",
    "cms": "MOC",
    "cnh": "MIT",
    "cons3rt": "Jackpine Technologies",
    "culbertj": "MGHPCC",
    "dasmith@ccs.neu.edu": "Northeastern University",
    "demo": "MOC",
    "dataspace": "Bentley",
    "duaat": "Boston University",
    "ec528-cloud-datacenter-scheduling" : "Boston University",
    "ec528-cloud-dataverse": "Boston University",
    "ec528-cloud-devops-resources": "Boston University",
    "ec528-location-aware-computing": "Boston University",
    "ec528-network-plugins-development": "Boston University",
    "ec528-network-plugins-optimization" : "Boston University",
    "ec528-radiology-cloud": "Boston University",                 
    "ec528-replicating-data-models": "Boston University",         
    "ec528-security-compliance-containers": "Boston University",  
    "ed1013@bu.edu": "Boston University",                        
    "fjansen": "Boston University",
    "frascog": "Boston University",
    "g.wang.china86": "University of Connecticut",
    "gshock@bu.edu": "Boston University",
    "gsilvis": "MOC",
    "henn": "MOC",
    "hpc": "MOC",
    "jfreud@bu.edu": "MOC",
    "jtgoodhue": "MGHPCC",
    "k2k": "MOC",
    "kamfonik": "MOC",
    "kapalavai.n@husky.neu.edu": "MOC",
    "katlaparthi.s": "MOC",
    "lapets": "Boston University",
    "larry.rudolph": "TwoSigma",
    "malte@csail.mit.edu": "MIT",
    "moc": "MOC",
    "naved001": "MOC",
    "nickolai": "MIT",
    "nikolaj": "Boston University",
    "okrieg": "MOC",
    "pjd@ccs.neu.edu": "MOC",
    "prajwal.maredukonda@philips.com": "Philips",
    "rahuls": "MOC",
    "ravig": "MOC",
    "ron.unrau": "General User",
    "rotemh": "MIT",
    "services": "MOC",
    "shreyap": "Boston University",
    "shwsun": "MOC",
    "small-brain": "Boston University",
    "sscheff": "Boston University",
    "supraja.krishnan7": "Northeastern University",
    "trtiwari@bu.edu": "MOC",
    "tutorial_2016": "MOC",
    "tutorial_project": "MOC",
    "tyroneh": "Boston University",
    "varia": "Boston University",
    "vinodv": "MIT",
    "weinbe2@bu.edu": "Boston University",
    "Elastic Prototype": "Boston University",                     
    "gnshealthcare": "GNS Health Care", 
    "HIL": "MOC",     
    "JAII -TEST": "Masstech",                            
    "jwa@bu.edu": "Boston University",               
    "koleinik": "Boston University",      
    "lily.sturmann": "Harvard University",        
    "moc-infrastructure": "MOC",                    
    "moc-tutorial": "MOC",               
    "Monitoring": "MOC",                  
    "Network Programmability": "Cisco",               
    "Network traffic collection in the MOC": "MOC", 
    "Nielsen Data Project": "Boston University",
    "NYC Subways": "Boston University",
    "primes-2017-monero": "PRIMES",       
    "Radiology in the Cloud": "Boston University",         
    "rstudio": "Smith College",
    "ryscheng": "University Of Washington",               
    "Secure Cloud": "MOC", 
    "Worldmap/BOP": "Harvard University",
    "IT Partners Research": "Boston University"  
}


